dist: focal
language: node_js
node_js:
  - "20"

cache:
  directories:
    - node_modules

script:
  - npm run build -s
  - npm run test -s
  - npm run lint -s

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
    node: "20"
